# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.TextField()),
                ('summary', models.TextField(null=True)),
                ('parsed', models.DateTimeField(default=datetime.datetime(2017, 5, 9, 21, 11, 40, 673394))),
                ('published', models.DateTimeField()),
                ('enclosure', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField()),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
            },
        ),
    ]
