# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='parsed',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 21, 35, 50, 560029)),
        ),
    ]
